services:
  image:  ahlbert-swiftdeploy:latest
  port: 9090
  mode: canary
  version: "1.0.0"
  restart_policy: unless-stopped

nginx:
  image: nginx:latest
  port: 5050
  proxy_timeout: 30

opa:
  policies_dir: ./policies
  host: localhost
  port: 8182        # host-side port the CLI uses to reach OPA

network:
  name: swiftdeploy-net
  driver_type: bridge

volumes:
  logs: swiftdeploy-logs